# hi-lite-golden-v1
# Scope categories are normalized to hi-lite semantic kinds.

line 1: 0..2=normal 2..3=normal 3..5=operator 5..6=normal 6..8=string
line 2: 0..6=normal 6..7=normal 7..9=operator 9..10=normal 10..27=string
line 3: 0..8=normal 8..9=normal 9..11=operator 11..12=normal 12..37=string
line 4: 0..5=normal 5..6=normal 6..8=operator 8..9=normal 9..14=string
line 5: 0..7=normal 7..8=normal 8..10=operator 10..11=normal 11..21=string
line 6: 0..7=normal 7..8=normal 8..10=operator 10..11=normal 11..23=string
line 7:
line 8: 0..6=function 6..7=operator 7..8=normal 8..22=string
line 9:
line 10: 0..3=function 3..4=operator 4..5=normal 5..19=string
line 11:
line 12: 0..2=macro 2..7=macro 7..8=macro 8..9=operator
line 13: 0..1=normal 1..6=normal 6..8=normal 8..9=normal 9..10=normal 10..12=macro
line 14:
line 15: 0..14=function 14..15=operator 15..16=normal 16..36=string
line 16: 0..1=normal 1..3=macro 3..5=macro 5..6=macro 6..7=normal 7..9=macro 9..15=macro 15..16=macro 16..17=normal 17..19=macro 19..26=macro 26..27=macro 27..28=normal 28..30=normal 30..31=normal 31..33=macro 33..34=normal 34..36=normal
line 17:
line 18: 0..12=function 12..13=operator 13..14=normal 14..51=string
line 19: 0..1=normal 1..3=macro 3..5=macro 5..6=macro 6..7=normal 7..9=macro 9..17=macro 17..18=macro 18..19=normal 19..21=macro 21..27=macro 27..28=macro 28..29=normal 29..38=normal 38..40=normal 40..43=normal 43..45=normal 45..47=normal 47..49=normal 49..50=normal 50..51=normal 51..53=macro 53..55=normal 55..56=normal 56..57=normal 57..59=macro
line 20:
line 21: 0..4=function 4..5=operator 5..6=normal 6..20=string
line 22: 0..1=normal 1..3=macro 3..8=macro 8..9=macro 9..18=normal 18..21=normal 21..30=normal
line 23:
line 24: 0..5=function 5..6=operator
line 25: 0..1=normal 1..3=normal 3..5=normal 5..7=normal 7..8=normal 8..10=macro 10..15=macro 15..16=macro
